name: 'Terraform'

on:
  release:
    types: [created]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      env:
        TF_LOG: TRACE
        TF_LOG_PATH: terraform-init.log

    - name: Terraform Plan
      run: terraform plan -out=jenkins.tfplan
      env:
        TF_LOG: TRACE
        TF_LOG_PATH: terraform-plan.log
        ARM_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.TF_AZURE_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TF_AZURE_TENANT }}

    - name: Terraform Apply
      run: terraform apply -auto-approve "jenkins.tfplan"
      env:
        TF_LOG: TRACE
        TF_LOG_PATH: terraform-apply.log
        ARM_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.TF_AZURE_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.TF_AZURE_TENANT }}
